language: php

env:
  global:
    - setup=basic

php:
  - 7.1
  - 7.2

matrix:
  include:
    - php: 7.1
      env: setup=stable
    - php: 7.2
      env: setup=stable

sudo: false

before_install:
  - phpenv config-rm xdebug.ini

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi

script: vendor/bin/phpunit
